### ISSUE TITLE
עמוד סטטיסטיקות

### ISSUE THREAD

**Issue by AdvaBitan21** [AdvaBitan21/IsraeliHope#3]

**Comment by daniellek12** [comment]
Created basic UI - we still need to decide which statistics we want to have (means what is the data to the PieChart)

**Comment by AdvaBitan21** [comment]
להוסיף היסטוגרמה של הציון בשאלון ראשון על פי הציון

**Comment by AdvaBitan21** [comment]
להוסיף גרף עוגה של הכמות המשתמשים על פי המגזר
